### GET ALL TEST
GET http://localhost:8080/movies


### GET ONE TEST
GET http://localhost:8080/movies/1


### CREATE TEST
POST http://localhost:8080/movies HTTP/1.1

{
    "Isbn":"33",
    "Title":"MovieOne",
    "Director":{"firstname":"post","lastname":"test"}
}

### UPDATE TEST
PUT http://localhost:8080/movies/2 HTTP/1.1

Content-Type: application/json
Accept: application/json

{
    "ID": "2",
    "Isbn":"33",
    "Title":"test title",
    "Director":{"firstname":"test","lastname":"taro"}
}


### DELETE TEST
DELETE http://localhost:8080/movies/1 HTTP/1.1

